### ISSUE TITLE
Error if destination file not found

### ISSUE THREAD

**Issue by seboschtion** [seboschtion/gummi#1]
```
sebastian@DESKTOP-8S4MPT1:/mnt/c/Users/sebastian/repos/labs/tcp-and-ip-performance$ gummi update --retry
Your document is out of date.
U? main/main.tex has changed locally and the template file has changed, too. Update the local file? If not, tracking will be lost. (yes, no) no
U? template/base.tex has changed locally and the template file has changed, too. Update the local file? If not, tracking will be lost. (yes, no) yes
U? template/pages/reset.tex has changed locally and the template file has changed, too. Update the local file? If not, tracking will be lost. (yes, no) yes
A: template/languages/de.tex
A: template/languages/en.tex
Traceback (most recent call last):
  File "/home/sebastian/.local/bin/gummi", line 11, in <module>
    sys.exit(main())
  File "/home/sebastian/.local/lib/python3.6/site-packages/gummi/main.py", line 51, in main
    return update(update_parser)
  File "/home/sebastian/.local/lib/python3.6/site-packages/gummi/main.py", line 91, in update
    return run_update(args.dry, args.retry)
  File "/home/sebastian/.local/lib/python3.6/site-packages/gummi/update.py", line 153, in run_update
    if not add(added) or not update(updated) or not delete(deleted):
  File "/home/sebastian/.local/lib/python3.6/site-packages/gummi/update.py", line 31, in update
    copy(original, local)
  File "/usr/lib/python3.6/shutil.py", line 245, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.6/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'part1/introduction.tex'
```

**Comment by seboschtion** [comment]
fixed in fc830ae0e72be50437c5e04bbd520b45a214e64f
